name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        JFROG_DOCKER_TOKEN : ${{secrets.JFROG_DOCKER_TOKEN}}
        JFROG_EMAIL : ${{secrets.JFROG_EMAIL}}
        JFROG_REPO : ${{secrets.JFROG_REPO}}
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        cat $HOME/.docker/config.json
        cd $HOME/.docker/
        jq '.auth[1] += {"JFROG_REPO" += {"auth" : "JFROG_DOCKER_TOKEN", "email" : JFROG_EMAIL}}' inputJson
        cat $HOME/.docker/config.json
        #docker login devopslv.jfrog.io
