name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      actions: read|write|none
      checks: read|write|none
      contents: read|write|none
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        JFROG_DOCKER_TOKEN : ${{secrets.JFROG_DOCKER_TOKEN}}
        JFROG_EMAIL : ${{secrets.JFROG_EMAIL}}
        JFROG_REPO : ${{secrets.JFROG_REPO}}
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        cat $HOME/.docker/config.json
        cd $HOME/.docker/
        ls -al
        jq '.auths = "Chocolate"' config.json
        #jq '.auth += {"JFROG_REPO" += {"auth" : "JFROG_DOCKER_TOKEN", "email" : JFROG_EMAIL}}' config
        cat $HOME/.docker/config.json
        #docker login devopslv.jfrog.io
