name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        
        JFROG_EMAIL : ${{secrets.JFROG_EMAIL}}
        JFROG_REPO : ${{secrets.JFROG_REPO}}
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
    - uses: jfrog/setup-jfrog-cli@v2  
      env:
        JFROG_DOCKER_TOKEN : ${{secrets.JFROG_DOCKER_TOKEN}}
    - run: |
        jfrog rt ping
        docker login devopslv.jfrog.io
